"""Paired Wilcoxon HC vs each TSFM on the canonical 5-seed scores (CHECK.md G4).

Reads the per-seed test accuracies that already live in
    outputs/canonical/<model>_<property>/canonical_results.json
    outputs/canonical_baselines/<property>/canonical_results.json
and computes paired (per-seed) Wilcoxon signed-rank tests for HC vs each TSFM
on every property. Reports raw and Holm-corrected p-values.

Output:
    outputs/paired_tests/wilcoxon_results.json
    outputs/paired_tests/wilcoxon_results.tex
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from scipy.stats import wilcoxon

OUT_DIR = Path("outputs/paired_tests")
OUT_DIR.mkdir(parents=True, exist_ok=True)

CANONICAL_ROOT = Path("outputs/canonical")
BASELINE_ROOT = Path("outputs/canonical_baselines")

MODELS = [
    "moment_pca512",
    "chronos",
    "patchtst_pretrained",
    "gpt4ts_pca512",
    "timer_meanpool",
    "timesfm_meanpool",
    "moirai_meanpool",
]
PROPERTIES = ["trend", "seasonality", "frequency", "stationarity", "anomaly", "change_point"]


def load_per_seed_canonical(model: str, prop: str) -> list[float] | None:
    p = CANONICAL_ROOT / f"{model}_{prop}" / "canonical_results.json"
    if not p.exists():
        return None
    return json.loads(p.read_text())["test_score_per_seed"]


def load_per_seed_baseline(prop: str, baseline: str) -> list[float] | None:
    p = BASELINE_ROOT / prop / "canonical_results.json"
    if not p.exists():
        return None
    rows = json.loads(p.read_text())
    for r in rows:
        if r["baseline"] == baseline:
            return r["per_seed_test"]
    return None


def holm_correct(pvals: list[float]) -> list[float]:
    """Holm-Bonferroni correction. Returns adjusted p-values."""
    arr = np.asarray(pvals, dtype=np.float64)
    n = len(arr)
    if n == 0:
        return []
    order = np.argsort(arr)
    adjusted = np.empty(n, dtype=np.float64)
    running_max = 0.0
    for rank, idx in enumerate(order):
        adj = arr[idx] * (n - rank)
        running_max = max(running_max, adj)
        adjusted[idx] = min(running_max, 1.0)
    return adjusted.tolist()


def main() -> None:
    rows: list[dict] = []

    for prop in PROPERTIES:
        hc = load_per_seed_baseline(prop, "hand_crafted")
        if hc is None:
            print(f"  SKIP {prop}: no HC baseline")
            continue
        for model in MODELS:
            tsfm = load_per_seed_canonical(model, prop)
            if tsfm is None:
                continue
            n = min(len(hc), len(tsfm))
            hc_arr = np.asarray(hc[:n], dtype=np.float64)
            tsfm_arr = np.asarray(tsfm[:n], dtype=np.float64)
            diff = hc_arr - tsfm_arr
            mean_diff = float(diff.mean())
            # Wilcoxon undefined when all diffs are zero (e.g., trend ceiling)
            try:
                stat, pval = wilcoxon(hc_arr, tsfm_arr, zero_method="wilcox")
                pval = float(pval)
                stat = float(stat)
            except ValueError:
                stat, pval = float("nan"), 1.0
            rows.append(
                {
                    "property": prop,
                    "model": model,
                    "hc_per_seed": [round(v, 4) for v in hc],
                    "tsfm_per_seed": [round(v, 4) for v in tsfm],
                    "hc_mean": round(hc_arr.mean(), 4),
                    "tsfm_mean": round(tsfm_arr.mean(), 4),
                    "mean_diff": round(mean_diff, 4),
                    "wilcoxon_stat": round(stat, 4) if stat == stat else None,
                    "p_value_raw": round(pval, 4),
                }
            )

    # Holm correction within each property (across 7 models).
    by_prop: dict[str, list[dict]] = {}
    for r in rows:
        by_prop.setdefault(r["property"], []).append(r)
    for _prop, prop_rows in by_prop.items():
        adj = holm_correct([r["p_value_raw"] for r in prop_rows])
        for r, p in zip(prop_rows, adj, strict=False):
            r["p_value_holm"] = round(p, 4)

    OUT_DIR.joinpath("wilcoxon_results.json").write_text(json.dumps(rows, indent=2))

    # LaTeX summary, one block per property.
    tex = [r"% Auto-generated by scripts/run_paired_wilcoxon.py"]
    tex.append(r"\begin{tabular}{llrrrrr}")
    tex.append(r"\toprule")
    tex.append(
        r"\textbf{Property} & \textbf{Model} & "
        r"\textbf{HC} & \textbf{TSFM} & "
        r"\textbf{HC$-$TSFM} & \textbf{$p$ (raw)} & \textbf{$p$ (Holm)} \\"
    )
    tex.append(r"\midrule")
    for r in rows:
        tex.append(
            f"{r['property']} & \\texttt{{{r['model']}}} & "
            f"{r['hc_mean']:.3f} & {r['tsfm_mean']:.3f} & "
            f"{r['mean_diff']:+.3f} & "
            f"{r['p_value_raw']:.3f} & {r['p_value_holm']:.3f} \\\\"
        )
    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    OUT_DIR.joinpath("wilcoxon_results.tex").write_text("\n".join(tex))

    print(
        f"{'Property':<14s} {'Model':<24s} {'HC':>6s} {'TSFM':>6s} "
        f"{'Diff':>7s} {'p_raw':>7s} {'p_holm':>8s}"
    )
    print("-" * 80)
    for r in rows:
        print(
            f"{r['property']:<14s} {r['model']:<24s} "
            f"{r['hc_mean']:>6.3f} {r['tsfm_mean']:>6.3f} "
            f"{r['mean_diff']:>+7.3f} {r['p_value_raw']:>7.3f} "
            f"{r['p_value_holm']:>8.3f}"
        )
    print(f"\nSaved to {OUT_DIR}")


if __name__ == "__main__":
    main()
