"""Paired-bootstrap p-value HC vs each TSFM on anomaly (REVIEW priority).

The 5-seed two-sided Wilcoxon signed-rank test cannot drop below p ~ 0.0625
(Wilcoxon floor at n = 5). To replace that floor-limited test, we compute a
paired bootstrap on the per-seed difference d_i = HC_i - TSFM_i (i = 1..5):

  - sample 10,000 paired bootstrap resamples of (HC_i, TSFM_i) with replacement
    over i = 1..5 (preserving pairing);
  - the per-seed difference is the test statistic;
  - the bootstrap p-value is 2 * min(P[d* <= 0], P[d* >= 0]) (two-sided).

We additionally compute Holm correction across the 7 TSFMs per property.

Output:
    outputs/paired_tests/paired_bootstrap_results.json
    outputs/paired_tests/paired_bootstrap_results.tex
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

OUT_DIR = Path("outputs/paired_tests")
OUT_DIR.mkdir(parents=True, exist_ok=True)

CANONICAL_ROOT = Path("outputs/canonical")
BASELINE_ROOT = Path("outputs/canonical_baselines")

MODELS = [
    "moment_pca512",
    "chronos",
    "patchtst_pretrained",
    "gpt4ts_pca512",
    "timer_meanpool",
    "timesfm_meanpool",
    "moirai_meanpool",
]
PROPERTIES = ["trend", "seasonality", "frequency", "stationarity", "anomaly", "change_point"]
N_BOOT = 10_000


def load_per_seed_canonical(model: str, prop: str) -> list[float] | None:
    p = CANONICAL_ROOT / f"{model}_{prop}" / "canonical_results.json"
    if not p.exists():
        return None
    return json.loads(p.read_text())["test_score_per_seed"]


def load_per_seed_baseline(prop: str, baseline: str) -> list[float] | None:
    p = BASELINE_ROOT / prop / "canonical_results.json"
    if not p.exists():
        return None
    rows = json.loads(p.read_text())
    for r in rows:
        if r["baseline"] == baseline:
            return r["per_seed_test"]
    return None


def paired_bootstrap_pvalue(
    a: np.ndarray, b: np.ndarray, n_boot: int = N_BOOT, seed: int = 42
) -> tuple[float, float, float, float]:
    """Returns (mean_diff, ci_low, ci_high, two_sided_p)."""
    rng = np.random.default_rng(seed)
    n = len(a)
    diffs = a - b
    obs = float(diffs.mean())
    # Bootstrap distribution of the mean difference.
    idx = rng.integers(0, n, size=(n_boot, n))
    boot = diffs[idx].mean(axis=1)
    ci_low, ci_high = np.percentile(boot, [2.5, 97.5])
    # Two-sided p-value: shift bootstrap to be centered at zero under H0.
    centered = boot - obs
    p_two = 2.0 * min((centered >= abs(obs)).mean(), (centered <= -abs(obs)).mean())
    p_two = float(np.clip(p_two, 1.0 / n_boot, 1.0))
    return obs, float(ci_low), float(ci_high), p_two


def holm_correct(pvals: list[float]) -> list[float]:
    arr = np.asarray(pvals, dtype=np.float64)
    n = len(arr)
    if n == 0:
        return []
    order = np.argsort(arr)
    adjusted = np.empty(n, dtype=np.float64)
    running_max = 0.0
    for rank, idx in enumerate(order):
        adj = arr[idx] * (n - rank)
        running_max = max(running_max, adj)
        adjusted[idx] = min(running_max, 1.0)
    return adjusted.tolist()


def main() -> None:
    rows: list[dict] = []

    for prop in PROPERTIES:
        hc = load_per_seed_baseline(prop, "hand_crafted")
        if hc is None:
            continue
        for model in MODELS:
            tsfm = load_per_seed_canonical(model, prop)
            if tsfm is None:
                continue
            n = min(len(hc), len(tsfm))
            a = np.asarray(hc[:n], dtype=np.float64)
            b = np.asarray(tsfm[:n], dtype=np.float64)
            md, lo, hi, pv = paired_bootstrap_pvalue(a, b)
            rows.append(
                {
                    "property": prop,
                    "model": model,
                    "n_seeds": int(n),
                    "hc_mean": round(float(a.mean()), 4),
                    "tsfm_mean": round(float(b.mean()), 4),
                    "mean_diff": round(md, 4),
                    "diff_ci95_low": round(lo, 4),
                    "diff_ci95_high": round(hi, 4),
                    "p_value_paired_bootstrap": round(pv, 5),
                }
            )

    by_prop: dict[str, list[dict]] = {}
    for r in rows:
        by_prop.setdefault(r["property"], []).append(r)
    for _prop, prop_rows in by_prop.items():
        adj = holm_correct([r["p_value_paired_bootstrap"] for r in prop_rows])
        for r, p in zip(prop_rows, adj, strict=False):
            r["p_value_holm"] = round(p, 5)

    OUT_DIR.joinpath("paired_bootstrap_results.json").write_text(json.dumps(rows, indent=2))

    tex = [r"% Auto-generated by scripts/run_paired_bootstrap.py"]
    tex.append(r"\begin{tabular}{llrrcrr}")
    tex.append(r"\toprule")
    tex.append(
        r"\textbf{Property} & \textbf{Model} & "
        r"\textbf{HC} & \textbf{TSFM} & \textbf{HC$-$TSFM (95\% CI)} & "
        r"\textbf{$p$ (boot)} & \textbf{$p$ (Holm)} \\"
    )
    tex.append(r"\midrule")
    for r in rows:
        model_tex = r["model"].replace("_", r"\_")
        ci_str = (
            f"${r['mean_diff']:+.3f}\\,[{r['diff_ci95_low']:+.3f},\\,"
            f"{r['diff_ci95_high']:+.3f}]$"
        )
        tex.append(
            f"{r['property']} & \\texttt{{{model_tex}}} & "
            f"{r['hc_mean']:.3f} & {r['tsfm_mean']:.3f} & "
            f"{ci_str} & "
            f"{r['p_value_paired_bootstrap']:.4f} & {r['p_value_holm']:.4f} \\\\"
        )
    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    OUT_DIR.joinpath("paired_bootstrap_results.tex").write_text("\n".join(tex))

    print(
        f"{'Property':<14s} {'Model':<24s} "
        f"{'HC':>6s} {'TSFM':>6s} {'Diff':>8s} {'p_boot':>8s} {'p_holm':>8s}"
    )
    print("-" * 80)
    for r in rows:
        print(
            f"{r['property']:<14s} {r['model']:<24s} "
            f"{r['hc_mean']:>6.3f} {r['tsfm_mean']:>6.3f} "
            f"{r['mean_diff']:>+8.3f} "
            f"{r['p_value_paired_bootstrap']:>8.4f} "
            f"{r['p_value_holm']:>8.4f}"
        )
    print(f"\nSaved to {OUT_DIR}")


if __name__ == "__main__":
    main()
